config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users
  resources :listings, except: [:create], shallow: true do
    resources :reservations, only: [:new, :create]
  end
  post '/listings/:listing_id/reservations/new', to: 'reservations#create'
  post '/listings/new', to: "listings#create"
  root 'pages#welcome'
  get '/welcome', to: 'pages#welcome'

  get '/listings/:id' => 'listings#show' 

  

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	
	belongs_to :user 
	has_many :reservations

	mount_uploader :image, ImageUploader


	validates :name, presence: true
	validates :description, presence: true
	validates :price, presence: true, numericality: true
	validate :image_size

	private

    # Validates the size of an uploaded picture.
    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "should be less than 5MB")
      end
    end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  # before_action :logged_in_user, only: [:create, :destroy]
  # before_action :correct_user,   only: :destroy

  # GET /listings
  # GET /listings.json
  def index
    # @user = current_user
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])
    @all_listings = current_user.listings
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.new(listing_params)
    if @listing.save!
 # Sends email to user after listing has been created     
  ExampleMailer.listing_confirmation(@listing).deliver_now     
      redirect_to listings_path
    else 
      render new
    # respond_to do |format|
    #   if @listing.save
    #     format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
    #     format.json { render :show, status: :created, location: @listing }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @listing.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    if current_user == @listing.user
      @listing.destroy
      redirect_to listings_path
    else 
      redirect_to listings_path
    end
    # respond_to do |format|
    #   format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
    #   format.json { head :no_content }
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :price, :description, :image)
    end

    # def correct_user
    #   @listing = current_user.image.find_by(id: params[:id])
    #   redirect_to root_url if @listing.nil?
    # end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_imageform.html.erb
<li id="listing-<%= image.id %>">
  <%= link_to gravatar_for(listing.user, size: 50), listing.user %>
  <span class="user"><%= link_to lsiting.user.name, micropost.user %></span>
  <span class="content">
    <%= listing.content %>
    <%= image_tag listing.picture.url if listing.image? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(listing.created_at) %> ago.
    <% if current_user?(listing.user) %>
      <%= link_to "delete", listing, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/listings/_links.html.erb
<%= link_to 'Logout', destroy_user_session_path, method: :delete %></a>

app/views/listings/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Find Your Castle", root_path, class: "navbar-brand bold"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar">
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
          <input type="text" class="form-control" placeholder="search away...">
    </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">What would you like to do?<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href='#'>Your Listings</li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li><a href="#">Account Settings</li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/listings/edit.html.erb
<h1>Edit Your Listing</h1>

<%= form_for :listing, html: {multipart: true} do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
  <div class="new-form">
  
  <fieldset class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, class: 'form-control', placeholder: 'Changes in pricing?' %>
  </fieldset>
  <fieldset class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control', placeholder: 'New additions to the premises?' %>
  </fieldset>
  <fieldset class="form-group">
    <% f.file_field :image, class: 'form-control' %>
  </fieldset>
  <%= f.submit "Update listing", class: "btn btn-primary"%>
</form>
<% end %>
</br>
</br>
<%= link_to 'Back', listings_path %>
<%= render 'links' %>
</div>
</div>
 
 

app/views/listings/index.html.erb
<%= render 'listings/navbar'%>

<div class="container">
  <div class="jumbotron listing_table_2">
    <h1>Listings</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= link_to listing.name, listing %></td>
        <td><%= listing.price %></td>
        <td><%= listing.description %></td>
        <td><%= listing.image %></td>
        <td><%= link_to 'Book now', new_listing_reservation_path(listing) %></td>
        <% if current_user.id == listing.user_id %>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Listing', new_listing_path %><br>
<%= render 'links' %>

  </div>
   </div>

app/views/listings/new.html.erb
<%= render 'navbar'%>

<%= form_for :listing, html: {multipart: true} do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="jumbotron listing_table_2" "well col-md-8 col-md-offset-2">
    <h1>Create Your Listing</h1>
      <fieldset class="form-group">
        <%= f.label :name%>
          <%= f.text_field :name, class: 'form-control', placeholder: 'Name and Address'%>
            <small class="text-muted">Specificity is key.</small>
      </fieldset>
      <fieldset class="form-group">
        <%= f.label :price %>
          <%= f.number_field :price, class: 'form-control'%>
      </fieldset>
      <fieldset class="form-group">
        <%= f.label :description %><br>
          <%= f.text_area :description, class: 'form-control', placeholder: 'Home amenities, style?' %>
      <small class="text-muted">Specific but brief</small>
      </fieldset>
      <fieldset class="form-group">
        <%= f.file_field :image , accept: 'image/jpeg,image/gif,image/png', class: 'form-control-file' %> 
        </fieldset>
          <%= f.submit "Create Lisiting", class: "btn btn-primary"%>
  <% end %>
</form>

</br>
</br>
<%= link_to 'Back', listings_path %><br>
<%= render 'links' %>

</div>
</div>

app/views/listings/show.html.erb
<%= render 'navbar'%>

<div class="container">
<div class="jumbotron listing_table_2">

<h1>Your New Listing</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Image</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @listing.name %></td>
        <td><%= @listing.price %></td>
        <td><%= @listing.description %></td>
        <td><%= image_tag @listing.image.url.to_s if @listing.image.url.present? %></td>
      </tr>
  </tbody>
</table>

<h1>All your listings</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Image</th>
    </tr>
  </thead>

  <tbody> 
    <% @all_listings.each do |listing| %>
      <tr>
        <td><%= listing.name %></td>
        <td><%= listing.price %></td>
        <td><%= listing.description %></td>
        <td><%= image_tag @listing.image.url.to_s if @listing.image.url.present? %></td>  
      </tr>
    <% end %>  
  </tbody>
</table>



<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>
<%= render 'links' %>

</div>
</div>

app/views/listings/show_current_user.html.erb
<!-- <h1>Your Listing</h1>

<% if current_user == @listing.user %>
<%= link_to 'Edit', edit_listing_path(@listing) %> 
<%else%>
<%= link_to 'Book', new_booking_path %>
<%end%>


<% @current_listing.each do |listing| %>
<%= listing.name %>
<% end %>
 -->